### ISSUE TITLE
Divination option blocks auto-Play.

### ISSUE THREAD

**Issue by SuperLargeEggplant** [aiczk/Astro#3] opened 2022-06-10 08:58 UTC
thanks for update

There still seems to be a bug with the Divination option.
I am checking with 0.0.1.2.

--
1. turn on all options. 
2. start the fight and use draw. 
3. use Malefic, but the play is not executed automatically.
   (If you do not target anything manually, the play is auto-targeted.)
   (Auto-targeting of Play, "If Divination is executable , stop auto play/redraw" option is in effect. )
4. use Divination.
5, When I do a Malefic, neither auto Play nor Redraw is executed as I want it to be.
6, After this, there is no automatic Play.
   I may be using only my environment, but with ver 0.0.1.1, ffxiv sometimes crashes.
--

1.turn on all options.
2. use Divination and wait for Divination's recast.
3. start combat and use Draw.
4. automatic Play should be executed, but it is not.

**Comment by aiczk** [comment] 2022-06-10 12:05
I'll try it. I'm sorry for the inconvenience.

**Comment by aiczk** [comment] 2022-06-10 12:21
Just out of curiosity, are the following four items correct for the problems that are currently occurring?
Or are the 5 hyphenated items also included?

**Comment by SuperLargeEggplant** [comment] 2022-06-10 12:33
They are both different things and it happens with each.
I am trying different things.
Sometimes it seems that even if I think it is not playing automatically, it will Play automatically after 1 GCD.

**Comment by aiczk** [comment] 2022-06-10 12:55
I have released ver 1.3 and you can check it out.
I think we were able to fix these problems by using the method of checking the recast timer seconds, as it was sometimes executed and sometimes not executed in our environment as well.

Regarding the option to stop autoplay/redraw when Divination is executable, am I correct in understanding that you want autoplay/redraw even when Divination is executable?

**Comment by SuperLargeEggplant** [comment] 2022-06-11 07:32
> Regarding the option to stop autoplay/redraw when Divination is executable, am I correct in understanding that you want autoplay/redraw even when Divination is executable?

I would like to 
When Divination is not available, autoplay/redraw is performed
When Divination is available autoplay/redraw stops.

Maybe this should be a separate Issue.
I think I may have figured out when the application crashes.
It seems that the application crashes when the Play button is pressed while no cards are being drawn.
The same thing happens in v1.3.


This is an addendum about the application crashing.
Normally, you do not need to press Play when you are not drawing a card, so you do not have to worry about application crashes.
I assume that if you hit the Play button repeatedly when manually Play, after the card has been played, Play may have been entered ahead of time without a card.

**Comment by SuperLargeEggplant** [comment] 2022-06-11 08:19
There are cases where AutoPlay still works as expected in v1.3, and there are cases where it does not.
Sometimes it would not AutoPlay with or without the Divination option.
Perhaps I was mistaken from the beginning.

When Astrodyne is buffed, it does not AutoPlay even if I keep running Malefic after Draw.

(I thought it might be a problem with Astrodyne's casting speed, so I checked the character's Spell Speed 400 and 1089, but that did not seem to be the problem.)

**Comment by aiczk** [comment] 2022-06-11 08:21
Thanks for the reply.

I will add "when not holding a card" to the conditional statement that is currently implemented "when not executing a play, it will execute some action that was performed as is".
It is more than possible that maybe Sloth or other combo plugin implementations are interfering with Astro's implementation, so I will look at the implementation and try to remove the cause of the crash.

I have created a new Issue on Divination.
Sorry, but please direct any complaints or requests about the autoplay/redraw behavior here.
https://github.com/aiczk/Astro/issues/4

**Comment by aiczk** [comment] 2022-06-11 08:25
We have confirmed a bug that prevents autoplay when Astrodyne is buffed, we will fix it immediately.

**Comment by aiczk** [comment] 2022-06-11 15:06
Fixed in ver 1.4

**Closed as completed by aiczk** 2022-06-11 15:06 UTC
Labels: bug
